### ISSUE TITLE
[BUG] Finetuning cannot accept `balancing` keys

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#161]
**Describe the bug and step to reproduce**
Add `balancing = smote` to [FEATS] with model type = finetune, the following error will occurs:

```
...
DEBUG: modelrunner: balancing the training features with: smote
Traceback (most recent call last):
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bagus/github/nkululeko/nkululeko/nkululeko.py", line 73, in <module>
    main(cwd)  # use this if you want to state the config file path on command line
  File "/home/bagus/github/nkululeko/nkululeko/nkululeko.py", line 68, in main
    doit(config_file)
  File "/home/bagus/github/nkululeko/nkululeko/nkululeko.py", line 53, in doit
    reports, last_epochs = expr.run()
  File "/home/bagus/github/nkululeko/nkululeko/experiment.py", line 614, in run
    self.runmgr.do_runs()
  File "/home/bagus/github/nkululeko/nkululeko/runmanager.py", line 56, in do_runs
    self.modelrunner = Modelrunner(
  File "/home/bagus/github/nkululeko/nkululeko/modelrunner.py", line 32, in __init__
    self._select_model(model_type)
  File "/home/bagus/github/nkululeko/nkululeko/modelrunner.py", line 132, in _select_model
    self._check_balancing()
  File "/home/bagus/github/nkululeko/nkululeko/modelrunner.py", line 249, in _check_balancing
    X_res, y_res = sampler.fit_resample(
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/site-packages/imblearn/base.py", line 208, in fit_resample
    return super().fit_resample(X, y)
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/site-packages/imblearn/base.py", line 106, in fit_resample
    X, y, binarize_y = self._check_X_y(X, y)
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/site-packages/imblearn/base.py", line 161, in _check_X_y
    X, y = self._validate_data(X, y, reset=True, accept_sparse=accept_sparse)
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/site-packages/sklearn/base.py", line 621, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1147, in check_X_y
    X = check_array(
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/site-packages/sklearn/utils/validation.py", line 797, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
  File "<__array_function__ internals>", line 200, in result_type
ValueError: at least one array or dtype is required
```

**Expected behavior**
No errors

**Desktop information**
 - OS:  Ubuntu 20.04
 - Nkululeko Version: 0.89.2

**Comment by bagustris** [comment]
Since `balancing` is in [FEATS] and the value of `type` is empty for fine-tuning, it is (very) difficult to adopt [FEATS] > balancing. One work around is to place `balancing` key in [MODEL] for fine-tuning model. E.g.,
```
[MODEL]
type = finetune
balancing = smote
```
I added the following balancing codes to `model_tuned.py`:
```INI
for split in ["train", "dev"]:
            df = data_sources[split]
            y = df[target_name].astype("float")
            y.name = "targets"
            df = y.reset_index()
            df.start = df.start.dt.total_seconds()
            df.end = df.end.dt.total_seconds()
        #     ds = datasets.Dataset.from_pandas(df)
        #     dataset[split] = ds

        # self.dataset = datasets.DatasetDict(dataset)
            if split == "train" and self.balancing:
                if self.balancing == "ros":
                    sampler = RandomOverSampler(random_state=42)
                elif self.balancing == "smote":
                    sampler = SMOTE(random_state=42)
                elif self.balancing == "adasyn":
                    sampler = ADASYN(random_state=42)
                else:
                    self.util.error(f"Unknown balancing algorithm: {self.balancing}")
                
                X_resampled, y_resampled = sampler.fit_resample(df[['start', 'end']], df['targets'])
                df = pd.DataFrame({'start': X_resampled['start'], 'end': X_resampled['end'], 'targets': y_resampled})
            
            ds = datasets.Dataset.from_pandas(df)
            dataset[split] = ds

        self.dataset = datasets.DatasetDict(dataset)
```

and it works.

What do you think @felixbur?   
Will submit a PR if you agree on this.
